### ISSUE TITLE
API docs do not show dedupe id in POST /clients response

### ISSUE THREAD

**Issue by eric-jahn** [hmis-api/2017-hmis-api#7]
https://hslynk.com/hmis-api/?urls.primaryName=2017%20Apis#/default/POST_clients
![screenshot_20181012-181548_chrome](https://user-images.githubusercontent.com/4115079/46884079-c6eba080-ce4b-11e8-83ca-4a095d2633fb.jpg)

same for older HMIS years

**Comment by suryayadavalli** [comment]
The documentation has been updated to reflect the changes below

1) Response for POST will return only client id
2) Response for GET to include dedupId
